#!/bin/bash

# Exit if hyprland is already locked.
[[ `hyprctl locked` = "true" ]] && exit 1

# Times the screen off and puts it to background
swayidle \
    timeout 15 'hyprctl dispatcher dpms off' \
    resume 'hyprctl dispatcher dpms on' &
hyprlock
# Kills last background task so idle timer doesn't keep running
kill %%
