#!/bin/sh

# sudo uclamp_hyprland&
FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0" swaync&
/usr/libexec/lxqt-policykit-agent&

sleep 3;
gammastep-indicator&
copyq &
nm-applet --indicator&
flatpak run com.nextcloud.desktopclient.nextcloud --background&
blueman-applet&
