#!/bin/sh

swaync&
lxqt-policykit-agent&
swayosd-server&
# Enable font "boldering" to increase visibility.
FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0" waybar&
kdeconnectd&

sleep 3;
copyq&
kdeconnect-indicator&
nm-applet --indicator&
flatpak run com.nextcloud.desktopclient.nextcloud --background&
blueman-applet&
