#!/bin/sh

swaync&
lxqt-policykit-agent&
# Enable font "boldering" to increase visibility.
FREETYPE_PROPERTIES="cff:no-stem-darkening=0 autofitter:no-stem-darkening=0" waybar --config ~/.config/waybar/config_hyprland&
kdeconnectd&

sleep 3;
gammastep-indicator&
copyq&
kdeconnect-indicator&
nm-applet --indicator&
flatpak run com.nextcloud.desktopclient.nextcloud --background&
