#!/bin/env bash

# Margin in screen ratio.
MARGIN_X=0.075
MARGIN_Y=0.4
BUTTONS=7

read -r x_resolution y_resolution < <(hyprctl -j monitors | jq -r ".[] |
    if .transform == 1 or .transform == 3 then
        select(.focused)
        | [.height / .scale, .width / .scale] | join(\" \")
    else
        select(.focused)
        | [.width / .scale, .height / .scale] | join(\" \")
    end")

# Detect monitor resolution and scaling factor
x_margin=$(awk "BEGIN {printf \"%.0f\", $x_resolution * $MARGIN_X}")
y_margin=$(awk "BEGIN {printf \"%.0f\", $y_resolution * $MARGIN_Y}")

if awk "BEGIN {exit !($x_resolution > 2100)}"; then
    wlogout -n -p layer-shell -b $BUTTONS -c 50 -r 50 -T $y_margin -B $y_margin -L $x_margin -R $x_margin
elif awk "BEGIN {exit !($x_resolution > 1900)}"; then
    # Apply a ratio .
    x_margin=$(awk "BEGIN {printf \"%.0f\", $x_margin * 0.6}")
    wlogout -n -p layer-shell -b $BUTTONS -c 50 -r 50 -T $y_margin -B $y_margin -L $x_margin -R $x_margin
elif awk "BEGIN {exit !($y_resolution > 1920)}"; then
    # Apply a ratio for 2 rows.
    y_margin=$(awk "BEGIN {printf \"%.0f\", $y_margin * 0.95}")
    wlogout -n -b 4 -c 50 -r 50 -T $y_margin -B $y_margin -L $x_margin -R $x_margin
else
    # Apply a ratio for 2 rows.
    y_margin=$(awk "BEGIN {printf \"%.0f\", $y_margin * 0.5}")
    wlogout -n -b 4 -c 50 -r 50 -T $y_margin -B $y_margin -L $x_margin -R $x_margin
fi
