#!/bin/env bash

# Margin in screen ratio.
MARGIN_X=0.15
MARGIN_Y=0.4
BUTTONS=6

read -r cursor_x cursor_y < <(hyprctl -j cursorpos | jq -r '[ .x, .y] | join(" ")')
read -r x_resolution y_resolution < <(hyprctl -j monitors | jq -r ".[] |
    if .transform == 1 or .transform == 3 then
        select(.x <= $cursor_x and (.x + .height / .scale) > $cursor_x and .y <= $cursor_y and (.y + .width / .scale) > $cursor_y)
        | [.height / .scale, .width / .scale] | join(\" \")
    else
        select(.x <= $cursor_x and (.x + .width / .scale) > $cursor_x and .y <= $cursor_y and (.y + .height / .scale) > $cursor_y)
        | [.width / .scale, .height / .scale] | join(\" \")
    end")

# Detect monitor resolution and scaling factor
x_margin=$(awk "BEGIN {printf \"%.0f\", $x_resolution * $MARGIN_X}")
y_margin=$(awk "BEGIN {printf \"%.0f\", $y_resolution * $MARGIN_Y}")

if awk "BEGIN {exit !($x_resolution > 2100)}"; then
    wlogout -n -p layer-shell -b $BUTTONS -c 50 -r 50 -T $y_margin -B $y_margin -L $x_margin -R $x_margin
elif awk "BEGIN {exit !($x_resolution == 1840)}"; then
    # Apply a ratio for a 16/10 2944x1840 screen with a scale of x1.6, lenovo slim 7x.
    y_margin=$(awk "BEGIN {printf \"%.0f\", $y_margin * 0.99}")
    x_margin=$(awk "BEGIN {printf \"%.0f\", $x_margin * 0.3}")
    wlogout -n -p layer-shell -b $BUTTONS -c 50 -r 50 -T $y_margin -B $y_margin -L $x_margin -R $x_margin
elif awk "BEGIN {exit !($x_resolution > 1800)}"; then
    # Apply a ratio on .
    x_margin=$(awk "BEGIN {printf \"%.0f\", $x_margin * 0.6}")
    wlogout -n -p layer-shell -b $BUTTONS -c 50 -r 50 -T $y_margin -B $y_margin -L $x_margin -R $x_margin
elif awk "BEGIN {exit !($y_resolution > 1920)}"; then
    # Apply a ratio for 2 rows.
    y_margin=$(awk "BEGIN {printf \"%.0f\", $y_margin * 0.95}")
    wlogout -n -b 4 -c 50 -r 50 -T $y_margin -B $y_margin -L $x_margin -R $x_margin
else
    # Apply a ratio for 2 rows.
    y_margin=$(awk "BEGIN {printf \"%.0f\", $y_margin * 0.3}")
    wlogout -n -b 4 -c 50 -r 50 -T $y_margin -B $y_margin -L $x_margin -R $x_margin
fi
