#!/bin/bash

autorandr -c -f
xrandr --dpi 96

bspc config wm_name             LG3D
bspc config border_width        1
bspc config window_gap          3
# Same color as background for active desktop in topbar.
bspc config presel_feedback_color \#FFC203

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config ignore_ewmh_focus   true
bspc config click_to_focus      button1
bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc monitor HDMI-A-0 -d d
bspc monitor DisplayPort-0 -d a
bspc monitor HDMI-A-1 -d s
bspc monitor -a f u i o p 7 8 9 0 ")"
# bspc monitor HDMI-0 -s DVI-D-0
bspc config top_padding 18

bspc rule -a '*:libreoffice' state=tiled

sleep 1
xsetroot -cursor_name left_ptr &
feh --bg-fill ~/.config/bspwm/wallpaper &
python ~/git/github/barython/test.py &
light-locker --no-lock-on-suspend &
xset -dpms &
xset s off &
xset -b &
setxkbmap -layout us -option compose:ralt &
xset r rate 333 35
picom --experimental-backends  &
if [ -e /usr/lib/geoclue-2.0/demos/agent ]; then
    /usr/lib/geoclue-2.0/demos/agent &
elif [ -e /usr/libexec/geoclue-2.0/demos/agent ]; then
    /usr/libexec/geoclue-2.0/demos/agent&
fi

if hash dispwin 2>/dev/null; then
    DISPWIN_HELP=`dispwin -h 2>&1`
    dispwin -d `echo "$DISPWIN_HELP" | grep HDMI-A-0 | awk '{print $1}'` ~/.config/bspwm/lg_ips236.icc
    dispwin -d `echo "$DISPWIN_HELP" | grep HDMI-A-1 | awk '{print $1}'` ~/.config/bspwm/dell_u2715h.icc
    dispwin -d `echo "$DISPWIN_HELP" | grep DisplayPort-0 | awk '{print $1}'` ~/.config/bspwm/lg_27gl850.icm
elif hash argyll-dispwin 2>/dev/null; then
    DISPWIN_HELP=`argyll-dispwin -h 2>&1`
    argyll-dispwin -d `echo "$DISPWIN_HELP" | grep HDMI-A-0 | awk '{print $1}'` ~/.config/bspwm/lg_ips236.icc
    argyll-dispwin -d `echo "$DISPWIN_HELP" | grep HDMI-A-1 | awk '{print $1}'` ~/.config/bspwm/dell_u2715h.icc
    argyll-dispwin -d `echo "$DISPWIN_HELP" | grep DisplayPort-0 | awk '{print $1}'` ~/.config/bspwm/lg_27gl850.icm
fi

sleep 1
/usr/lib64/xfce4/notifyd/xfce4-notifyd&
nm-applet &
redshift-gtk &
clipit &
nextcloud &
sxhkd &
kdeconnect-indicator&
fcitx&

sleep 2
if hash trayer 2>/dev/null; then
    trayer --edge top --align right --expand false --margin 300 --widthtype request --height 18 --alpha 0 --transparent true --tint 0xFF2d2d2d --monitor "primary" --SetDockType true  --iconspacing 5 &
elif hash trayer-srg 2>/dev/null; then
    trayer-srg --edge top --align right --expand false --margin 300 --widthtype request --height 18 --alpha 0 --transparent true --tint 0xFF2d2d2d --monitor "primary" --SetDockType true  --iconspacing 5 &
fi
lxqt-policykit-agent&

sleep 1
xdo above -t $(xwininfo -root -children  | egrep -o "^ +.x[^ ]+" | tail -1 | tr -d " ") $(xdo id -a panel) $(xdo id -a bar)
