#!/bin/bash

xrandr --dpi 115
bspc config wm_name             LG3D
bspc config border_width        1
bspc config window_gap          4

bspc config split_ratio         0.5
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config top_monocle_padding 1
bspc config right_monocle_padding 1
bspc config left_monocle_padding 1
bspc config bottom_monocle_padding 1
bspc config single_monocle true
bspc config ignore_ewmh_focus   true
bspc config click_to_focus      button1
bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc monitor eDP-1 -d a
bspc monitor HDMI-1 -d "="
bspc monitor -a  s d f u i o p 7 8 9 0 ")"
bspc config top_padding 22

bspc rule -a '*:libreoffice' state=tiled

sleep 1
xsetroot -cursor_name left_ptr &
autorandr -c
feh --bg-fill ~/.config/bspwm/wallpaper &
~/git/github/barython/laptop.py &
light-locker --lock-on-suspend --lock-after-screensaver=3  &
xset dpms 180 180 180 &
xset -b &
xset s 180 &
setxkbmap -layout us -option compose:ralt &
xset r rate 333 35
xinput set-prop "DLL07BE:01 06CB:7A13 Touchpad" "libinput Tapping Enabled" 1
# Set the minimum brightness to 1 (avoid black screen)
light -S -c 1 &
picom --experimental-backends  &
/usr/lib/geoclue-2.0/demos/agent &

DISPWIN_HELP=`dispwin -h 2>&1`
dispwin -d `echo "$DISPWIN_HELP" | grep eDP-1 | awk '{print $1}'` ~/.config/bspwm/screen_calib.icc

sleep 1
nm-applet &
redshift-gtk &
clipit &
nextcloud &
sxhkd &
indicator-kdeconnect&
fcitx&

sleep 2
trayer --edge top --align right --expand false --margin 492 --widthtype request --height 22 --alpha 0 --transparent true --tint 0xFF2d2d2d --monitor "primary" --SetDockType true --SetPartialStrut false --iconspacing 5 &
/usr/lib/xfce-polkit/xfce-polkit &

sleep 1
xdo above -t $(xwininfo -root -children  | egrep -o "^ +.x[^ ]+" | tail -1 | tr -d " ") $(xdo id -a panel) $(xdo id -a bar)
bluetooth off
