#!/bin/sh

bspc config wm_name             LG3D
bspc config border_width        1
bspc config window_gap          3

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_by_distance   true
bspc config ignore_ewmh_focus   true
bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors false

bspc monitor HDMI-0 -d s
bspc monitor DVI-D-0 -d a
bspc monitor DVI-I-0 -d d
bspc monitor -a d f u i o p 7 8 9 0 ")"
bspc monitor HDMI-0 -s DVI-D-0
bspc config top_padding 18

### Rules ###
D_MSGING=i
bspc rule -a Thunderbird desktop=$D_MSGING split_ratio=0.3
bspc rule -a Pidgin desktop=$D_MSGING split_ratio=0.7

sleep 1
xsetroot -cursor_name left_ptr &
nvidia-settings --load-config-only &
feh --bg-fill ~/.config/qtile/wallpaper.jpg &
# ~/.config/bspwm/panel &
bspc config top_padding 18
~/git/github/barython/test.py &
light-locker --no-lock-on-suspend &
xset dpms 180 180 180 &
xset s 180 &
xset -b &
setxkbmap -layout us -option compose:ralt &
compton -cG --backend glx --unredir-if-possible &

sleep 1
nm-applet &
pa-applet &
redshift-gtk &
clipit &
owncloud &
sxhkd &
