general {
    lock_cmd = ~/.config/hypr/scripts/is_locked || hyprlock
    unlock_cmd = pkill -USR1 hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action="on"})'
    ignore_dbus_inhibit = false
}

listener {
    timeout = 10
    on-timeout = ~/.config/hypr/scripts/is_locked && hyprctl dispatch 'hl.dsp.dpms({action="off"})' # turn off the screen on lockscreen
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action="on"})'
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 310
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action="off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action="on"})'
}
