general {
    lock_cmd = ~/.config/hypr/scripts/is_locked || hyprlock
    unlock_cmd = pkill -USR1 hyprlock
    after_sleep_cmd = sleep 0.5; hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout = 10
    on-timeout = ~/.config/hypr/scripts/is_locked && hyprctl dispatch dpms off # turn off the screen on lockscreen
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 610
    on-timeout = sudo /usr/local/bin/cpupower_gov powersave
    on-resume = sudo /usr/local/bin/cpupower_gov performance
}

listener {
    timeout = 3600
    on-timeout = systemctl suspend
}
