"hyprland.lua": "~/.config/hypr/hyprland.lua"
"hyprlock.conf": "~/.config/hypr/hyprlock.conf"
"hypridle.conf": "~/.config/hypr/hypridle.conf"
"conf": "~/.config/hypr/conf"
"scripts": "~/.config/hypr/scripts"
"wallpaper": "~/.config/hypr/wallpaper"
"wallpaper-lockscreen": "~/.config/hypr/wallpaper-lockscreen.png"
