#!/bin/bash

hyprctl dispatch exec "[workspace 1 silent]" -- firefox
~/.config/hypr/scripts/wait_for -t 5 "select(.class | startswith(\"firefox\"))"
hyprctl dispatch movetoworkspacesilent 1,'class:^firefox.*$'
