#!/bin/bash

_WORKSPACE=2
_SPLIT_RATIO=1.6
_DIR=UP
_THUNDERBIRD_CMD=thunderbird

# Disable autofocus.
hyprctl -q keyword windowrulev2 'noinitialfocus, class:.*'

_current_focus_addr=$(hyprctl -j activewindow | jq -r .address)

_foot_addr=$(~/.config/hypr/scripts/wait_for "select((.class | startswith(\"foot\")) and (.workspace.id == $_WORKSPACE))")
if [ -n "$_foot_addr" ]; then
    hyprctl -q dispatch focuswindow "address:$_foot_addr"
else
    hyprctl -q dispatch workspace $_WORKSPACE
fi

hyprctl -q dispatch layoutmsg "preselect u"
hyprctl -q dispatch splitratio exact $_SPLIT_RATIO

hyprctl -q dispatch exec $_THUNDERBIRD_CMD

_thunderbird_addr=$(~/.config/hypr/scripts/wait_for -t 5 "select(.class | startswith(\"thunderbird\"))")
hyprctl -q dispatch focuswindow "address:$_thunderbird_addr"
hyprctl -q dispatch splitratio exact $_SPLIT_RATIO
hyprctl -q dispatch focuswindow "address:$_current_focus_addr"

# Reenable autofocus.
hyprctl -q keyword windowrulev2 'unset, noinitialfocus, class:.*'
