monitor = , preferred, auto, auto

monitorv2 {
    output = desc:LG Electronics 27GL850 912NTWG0N049
    mode = preferred
    position = auto
    bitdepth = 10
    cm = dp3
    supports_hdr = -1
}

monitorv2 {
    output = desc:Microstep MPG321UX OLED 0x01010101
    mode = 3840x2160@239.99Hz
    position = auto
    max_luminance = 500
    max_avg_luminance = 500
    sdr_max_luminance = 200
}

monitorv2 {
    output = desc: Dell Inc. DELL U2715H GH85D83V2Q6S
    mode = 2560x1440@59.95100Hz
    position = auto
}
