permission = /usr/bin/grim, screencopy, allow
permission = /usr/bin/hyprshot, screencopy, allow
permission = /usr/bin/hyprlock, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
