windowrule = float on, match:class org.kde.polkit-kde-authentication-agent-1
windowrule = float on, match:title Confirm to replace files
windowrule = float on, match:class file_progress
windowrule = float on, match:title File Operation Progress
windowrule = float on, match:class confirm
windowrule = float on, match:class dialog
windowrule = float on, match:class download
windowrule = float on, match:class notification
windowrule = float on, match:class error
windowrule = float on, match:class splash
windowrule = float on, match:title confirmreset
windowrule = float on, match:title Open File
windowrule = float on, match:title branchdialog
windowrule = float on, match:title (V|v)iewnior
windowrule = float on, match:class pavucontrol-qt
windowrule = float on, match:class pavucontrol
windowrule = float on, match:class file-roller
windowrule = float on, match:title ^(Media viewer)$
windowrule = float on, match:title ^(Volume Control)$
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(thunderbird)$, match:title ^(.*)(Reminder)(.*)$

layerrule = match:namespace logout_dialog, blur on
layerrule = match:namespace wofi, blur on, ignore_alpha 0.5
