
# If not running interactively, don't do anything
[[ $- != *i* ]] && return


# Functions
####################
function mkdir_cd {
    mkdir $1 && cd $1;
}

function clean_cache {
    sync
    su -c "echo 3 > /proc/sys/vm/drop_caches"
}

function compile_options {
    compilator=$1
    binary=$2
    shift; shift
    src=$*
    $compilator -O2 -Wall -Werror -Wextra -ansi -pedantic -D_POSIX_SOURCE \
        -pthread -o $binary $src
}

function compile_options_debug {
    compilator=$1
    binary=$2
    shift; shift
    src=$*
    $compilator -g -Wall -Wextra -Werror -ansi -pedantic -D_POSIX_SOURCE \
        -pthread -o $binary $src
}


# Alias
####################

# One-key aliases
alias b='vim ~/blocnote'
alias e='exit'
alias g='git'
alias l='ls'
alias n='newurxvt'
alias p='ping'
alias v='vim'

alias ls='ls --color=auto'
alias ll='ls -alh'
alias cp='cp -r --reflink=auto'
alias mkcd=mkdir_cd $1
alias maj='sudo yaourt -Syua && sudo pacman -Su && sudo cnf-sync'
alias hibernate='systemctl hibernate'
alias gitlog='git log --color'
alias free='free -h'
alias grep='grep --color'
alias sudo='sudo ' # Make aliases work with sudo

# Firefox
alias firefox-beta='firefox-beta-bin -p beta -no-remote'
alias firefox-aurora='firefox-aurora -p beta -no-remote'
alias firefox-clean='firefox -p clean -no-remote'

# Compile
alias gcco='compile_options gcc $*'
alias gccod='compile_options_debug g++ $*'
alias clango='compile_options clang $*'
alias clangod='compile_options_debug clang $*'
alias clang++o='compile_options clang++ $*'
alias clang++od='compile_options_debug clang++ $*'
alias g++o='compile_options g++ $*'
alias g++od='compile_options_debug g++ $*'

# SSH
alias ssh-aruhier='ssh -x anthony@aruhier.fr'

# urxvt
alias newurxvt='urxvt&; disown %urxvt'


# XModMap
####################

#xmodmap /home/anthony/.xmodmap.conf


# HISTORIQUE
####################
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt hist_ignore_all_dups
setopt sharehistory


# Other
####################

export PS1="%n@%U%m%u> "

# Compatibilité avec gnome-terminal
export PS1='%{$(__vte_ps1)%}'$PS1
. /etc/profile.d/vte.sh

export TERM=xterm-256color
export EDITOR=vim
if [ -f ~/.dir_colors/dircolors ]
    then eval `dircolors ~/.dir_colors/dircolors`
fi

# The following lines were added by compinstall
zstyle ":completion:*:commands" rehash 1 menu select
zstyle :compinstall filename '/home/anthony/.zshrc'

#setopt completealiases
#setopt correctall

# Syntax highlighting
if [ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]
    then source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

autoload -Uz compinit promptinit
compinit
promptinit

# This will set the default prompt to the walters theme
prompt walters

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt hist_ignore_space
# End of lines configured by zsh-newuser-install


# Special keys solution
####################

autoload zkbd
function zkbd_file() {
    [[ -f ~/.zkbd/${TERM}-${VENDOR}-${OSTYPE} ]] && printf '%s' ~/".zkbd/${TERM}-${VENDOR}-${OSTYPE}" && return 0
    [[ -f ~/.zkbd/${TERM}-${DISPLAY}          ]] && printf '%s' ~/".zkbd/${TERM}-${DISPLAY}"          && return 0
    return 1
}

[[ ! -d ~/.zkbd ]] && mkdir ~/.zkbd
keyfile=$(zkbd_file)
ret=$?
if [[ ${ret} -ne 0 ]]; then
    zkbd
    keyfile=$(zkbd_file)
    ret=$?
fi
if [[ ${ret} -eq 0 ]] ; then
    source "${keyfile}"
else
    printf 'Failed to setup keys using zkbd.\n'
fi
unfunction zkbd_file; unset keyfile ret

# setup key accordingly
[[ -n "${key[Home]}"    ]]  && bindkey  "${key[Home]}"    beginning-of-line
[[ -n "${key[End]}"     ]]  && bindkey  "${key[End]}"     end-of-line
[[ -n "${key[Insert]}"  ]]  && bindkey  "${key[Insert]}"  overwrite-mode
[[ -n "${key[Delete]}"  ]]  && bindkey  "${key[Delete]}"  delete-char
[[ -n "${key[Up]}"      ]]  && bindkey  "${key[Up]}"      up-line-or-history
[[ -n "${key[Down]}"    ]]  && bindkey  "${key[Down]}"    down-line-or-history
[[ -n "${key[Left]}"    ]]  && bindkey  "${key[Left]}"    backward-char
[[ -n "${key[Right]}"   ]]  && bindkey  "${key[Right]}"   forward-char
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5C" emacs-forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5D" emacs-backward-word
bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^[[Z" reverse-menu-complete # Shift+Tab
bindkey "^[[3;5~" kill-word            # Ctrl+Delete
bindkey '^R' history-incremental-search-backward
bindkey '^S' history-incremental-search-forward
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward

# Fix de ^M bug when typing "enter" sometimes
stty icrnl
