node.rules = [
  {
    matches = [
      {
        "node.name" = "~.*"
      }
    ]
    actions = {
      update-props = {
        "resample.quality" = 10
      }
    }
  }
]

monitor.alsa.rules = [
  {
    matches = [
      {
        "node.name" = "~.*"
      }
    ]
    actions = {
      update-props = {
        "resample.quality" = 10
      }
    }
  }
]
