monitor.alsa.rules = [
  {
    matches = [
      {
        "node.name" = "~.*Grace_Design_SDAC.*"
      }
    ]
    actions = {
      update-props = {
        "audio.format"        = "S24_3LE",
        "audio.rate"          = 96000,
        "resample.quality"    = 10,
      }
    }
  }
]
