# Everforest dark
[colors-dark]
alpha=1.0
background=2d353b
foreground=d3c6aa

regular0=475258 # black
regular1=e67e80 # red
regular2=a7c080 # green
regular3=dbbc7f # yellow
regular4=7fbbb3 # blue
regular5=d699b6 # magenta
regular6=83c092 # cyan
regular7=d3c6aa # white

bright0=475258 # black
bright1=e67e80 # red
bright2=a7c080 # green
bright3=dbbc7f # yellow
bright4=7fbbb3 # blue
bright5=d699b6 # magenta
bright6=83c092 # cyan
bright7=d3c6aa # white

# Everforest dark
[colors-light]
alpha=1.0
background=fdf6e3
foreground=5c6a72

regular0=5c6a72 # black
regular1=f85552 # red
regular2=8da101 # green
regular3=dfa000 # yellow
regular4=3a94c5 # blue
regular5=df69ba # magenta
regular6=35a77c # cyan
regular7=e0dcc7 # white

bright0=5c6a72 # black
bright1=f85552 # red
bright2=8da101 # green
bright3=dfa000 # yellow
bright4=3a94c5 # blue
bright5=df69ba # magenta
bright6=35a77c # cyan
bright7=e0dcc7 # white
